POST localhost:8080/article/adm/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTY0MTc4NjEsImV4cCI6MTY1NjYzMzg2MSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyLCJyb2xlIjoiTU9ERVJBVE9SIn0.dwSAV1G5zQGN3r8nfBiHud6oJHcgpYP7NPdxhMWDBBQ

{
  "title": "abduVali oldirildi",
  "description": "achki",
  "regionId": 1,
  "categoryId": 1,
  "typesList":[1],
  "tagList": ["#achki","#piyola","#eshak"],
  "photoId": "8a8a85a28185e841018185e921e30000",
  "content": "qasiz brat"

}
###

GET localhost:8080/article/region/1


###
DELETE  localhost:8080/article/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ5NzM2NTAsImV4cCI6MTY1NDk3NzI1MCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyLCJyb2xlIjoiTU9ERVJBVE9SIn0.Uo2GwpT0MYMwzZbZQr7o3KVipM_VasxsXdDL0_1m1VI

{
  "id": "4028818b8152554e01815257b2480001"
}

###
 PUT localhost:8080/article/adm/publish
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTU0NjQzMDQsImV4cCI6MTY1NTY4MDMwNCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjo0LCJyb2xlIjoiUFVCTElTSEVSIn0.3_8dEJkoDJPyiC-_wbUNJCg7V7jqtz5ZgrhpNUoqJSc

{
  "id":"4028818b8152554e01815257b2480001"

}
###
POST localhost:8080/article/last8
Content-Type: application/json

{
 "idList": ["402881858152fcff0181530537ef0001","4028818b8152554e01815257b2480001"]
}

###
PUT localhost:8080/article/like
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTUwMjQxNTIsImV4cCI6MTY1NTAyNzc1MiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjo1LCJyb2xlIjoiVVNFUiJ9._-1csIW1fdJuTtsVq6HGJRAo38fUcjXuds8AGdZ24fs

{
  "id": "1"
}
###
GET localhost:8080/article/region/assalomu alaykum1

###
POST  localhost:8080/article/filter
Content-Type: application/json


{

 "regionId": 1,
  "description": "juratli inson"
}
###
GET http://localhost:8080/article/category/333333?page=0&size1



