POST localhost:8080/category/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTUyOTc5MDAsImV4cCI6MTY1NTMwMTUwMCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.0Gie-VdHpQv7telmFrq7OJKMf1T2TI8z4aiT2VZ_-pQ

{

  "nameUz": "intervyu",
  "nameRu": "intervyu",
  "nameEn": "interview",
  "key": "3333331"

}
###
PUT localhost:8080/category/update
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ3ODQwNDMsImV4cCI6MTY1NDc4NzY0MywiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.7UcudZ1_vgzVoJWWxb7OqoL1SNjYmkDr6p0kFAHJbMI

{
  "id": 1,
   "nameUZ": "jizzax1",
  "nameRU": "JIZZAX1",
  "nameENG": "Jizzakh1"
}
###
GET localhost:8080/category/list
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ3ODQwNDMsImV4cCI6MTY1NDc4NzY0MywiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.7UcudZ1_vgzVoJWWxb7OqoL1SNjYmkDr6p0kFAHJbMI

###
DELETE localhost:8080/category/delete
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ3ODQwNDMsImV4cCI6MTY1NDc4NzY0MywiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.7UcudZ1_vgzVoJWWxb7OqoL1SNjYmkDr6p0kFAHJbMI

{
  "id": 1
}