POST localhost:8080/profile/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ5NDIxNzEsImV4cCI6MTY1NDk0NTc3MSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.a4wlEP7U1BwNN0PYr9Ui4UhGgFO-BlebR6fy1xJn1AU

{
  "name": "jahon",
  "surName": "qalesiz",
  "email": "@gmail12",
  "password": "1111",
  "role": "MODERATOR"
}
###
PUT localhost:8080/profile/update
Content-Type: application/json
Authorization:  eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ3NTY4NjIsImV4cCI6MTY1NDc2MDQ2MiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.r8QxeV7kSg3SnggCFr7NOfWQAiqnadToyQm9hH9RRVo

{
  "id": 1,
  "name": "jahon",
  "surname": "qale",
  "password": "1111"
}
###
GET localhost:8080/profile/list
Authorization:   eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ3NTk0NjcsImV4cCI6MTY1NDc2MzA2NywiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjozLCJyb2xlIjoiUFVCTElTSEVSIn0.RmlkezDmhOcXwInH1BevhYWZxc_NMlpSYtr1mo-mhDE