POST localhost:8080/profile/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTY0MTk2MDcsImV4cCI6MTY1NjYzNTYwNywiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.XR5EXHO6y7qgNP1QUn4E12d_nb8ZiVfqDtpIpRJgcyE

{
  "name": "jahon",
  "surname": "qalesiz",
  "email": "@gmail121222",
  "password": "1111",
  "role": "USER",
  "photoId": "40288186818c7a7b01818c7a95b40000"
}
###
PUT localhost:8080/profile/update
Content-Type: application/json
Authorization:  eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ3NTY4NjIsImV4cCI6MTY1NDc2MDQ2MiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.r8QxeV7kSg3SnggCFr7NOfWQAiqnadToyQm9hH9RRVo

{
  "id": 1,
  "name": "jahon",
  "surname": "qale",
  "password": "1111"
}
###
GET localhost:8080/profile/adm/filter
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTYyNzI2MDAsImV4cCI6MTY1NjQ4ODYwMCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.RfwOasz6Lr1AQPubXle2DvNYdaspYiUbEJj-fCrcUG0

{
  "surname": "Omonxonov",
  "role": "ADMIN"

}
