POST localhost:8080/comment/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTUzNzI2NjcsImV4cCI6MTY1NTU4ODY2NywiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.pGSDmgoc0tETxLQ1uryhW548FCLGf3ekNZk-aejdqvs

{
"content": "qalesiz ozizcha yaxshi ish qildingizda aa",
  "articleId":"402881888153c6d1018153c898080000"

}

###

PUT localhost:8080/comment/
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTUzNzI2NjcsImV4cCI6MTY1NTU4ODY2NywiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.pGSDmgoc0tETxLQ1uryhW548FCLGf3ekNZk-aejdqvs

{
"content": " update",
"articleId":"402881888153c6d1018153c898080000",
  "id": 5
}

###
PUT localhost:8080/comment/adm/commentListForAdmin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTUzNzMzNzYsImV4cCI6MTY1NTU4OTM3NiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.3vFtAy_FsyUmUAUjnUX6wHgiBtVsVd9AvR_sHHZve8M

